
from decimal import Decimal


POLICY_VERSION = "EC_POLICY_V1"
CURRENCY_BRL = "BRL"
MONEY_TOLERANCE_BRL = Decimal("0.10")

ISSUE_VALID_SPLIT_PAYMENT = "valid_split_payment"
ROOT_CAUSE_MULTIPLE_PAYMENTS_RECONCILED = "MULTIPLE_PAYMENTS_RECONCILED"
ACTION_EXPLAIN_VALID_SPLIT_PAYMENT = "explain_valid_split_payment"

RESPONSIBLE_PARTY_NONE = "none"

MAX_ENTITY_IDS = 5
MAX_EVIDENCE_IDS = 10
